const texts = [
    'Ukraine is a country in Eastern Europe. It is the second-largest European country after Russia, which it borders to the east and northeast. Pre-war Ukraine covered approximately 600,000 square kilometres, and was the eighth-most populous country in Europe, with a population of around 41 million people',
    'The Ukrainian units entered Kupyansk, the liberation of localities of Kupyansk and Izium districts of Kharkiv region continues.',
    'The Armed Forces of Ukraine released a video showing the elimination of about 30 Russians and their equipment in Kharkiv direction.',
    'A fully independent Ukraine emerged only late in the 20th century, after long periods of successive domination by Poland-Lithuania, Russia, and the Union of Soviet Socialist Republics (U.S.S.R.). Ukraine had experienced a brief period of independence in 1918–20, but portions of western Ukraine were ruled by Poland, Romania, and Czechoslovakia in the period between the two World Wars, and Ukraine thereafter became part of the Soviet Union as the Ukrainian Soviet Socialist Republic (S.S.R.)',
    'Ukraine is bordered by Belarus to the north, russia to the east, the Sea of Azov and the Black Sea to the south, Moldova and Romania to the southwest, and Hungary, Slovakia, and Poland to the west. In the far southeast, Ukraine is separated from russia by the Kerch Strait, which connects the Sea of Azov to the Black Sea.',
    'Ukraine occupies the southwestern portion of the Russian Plain (East European Plain). The country consists almost entirely of level plains at an average elevation of 574 feet (175 metres) above sea level. Mountainous areas such as the Ukrainian Carpathians and Crimean Mountains occur only on the country’s borders and account for barely 5 percent of its area. The Ukrainian landscape nevertheless has some diversity: its plains are broken by highlands—running in a continuous belt from northwest to southeast—as well as by lowlands',
    'The rolling plain of the Dnieper Upland, which lies between the middle reaches of the Dnieper (Dnipro) and Southern Buh (Pivdennyy Buh, or the Boh) rivers in west-central Ukraine, is the largest highland area; it is dissected by many river valleys, ravines, and gorges, some more than 1,000 feet (300 metres) deep. On the west the Dnieper Upland is abutted by the rugged Volyn-Podilsk Upland, which rises to 1,545 feet (471 metres) at its highest point, Mount Kamula. West of the Volyn-Podilsk Upland, in extreme western Ukraine, the parallel ranges of the Carpathian Mountains—one of the most picturesque areas in the country—extend for more than 150 miles (240 km). The mountains range in height from about 2,000 feet (600 metres) to about 6,500 feet (2,000 metres), rising to 6,762 feet (2,061 metres) at Mount Hoverla, the highest point in the country. The northeastern and southeastern portions of Ukraine are occupied by low uplands rarely reaching an elevation of 1,000 feet (300 metres).'
]

export default texts;
